name: Test code and push to branch

on:
  push:
    branches:
      - main
      - springboot2
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test code
        run: mvn test -Dmaven.test.skip=false
      - name: Merge to staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: staging
          github_token: ${{ github.token }}
